### ISSUE TITLE
IUS-COMMUNITY-EUA is world-writable (0666), should be 0644

### ISSUE THREAD

**Issue by rgm3** [iuscommunity-pkg/ius-release#4]
Full path to file is `/usr/share/doc/ius-release-1.0/IUS-COMMUNITY-EUA`.  This shows up as a "severe vulnerability" (which it is clearly not) when security scanning software such as Rapid7 Nexpose is used to audit a system.

**Comment by carlwgeorge** [comment]
That is certainly odd.  Checking the spec file, we aren't explicitly setting that permission.  The file is put in place by the `%doc` macro, which appears to just preserve the permissions of the file.  That file was originally [imported from Launchpad](https://github.com/iuscommunity-pkg/ius-release/commit/df483f2bf0872ecc70d5b1a5f165699aeb9d898c), so I wonder if that has something to do with it.  I'll look into how to fix this.

**Comment by carlwgeorge** [comment]
We were able to narrow this down to a misuse of `cp` in `%prep`.  Somehow our build automation was cloning the repo with 777/666 permissions, and the `%{__cp} -p` was preserving those permissions, rather than letting mock use the normal umask.  It wasn't a problem for files that were put into the buildroot with `install` (manually setting the correct permissions), but that one particular file is moved into place with the `%doc` macro, which also preserves permissions.

**Comment by carlwgeorge** [comment]
New builds are in progress, and will get published to the testing repositories during tonight's automation.

**Comment by carlwgeorge** [comment]
The fix is now in the stable repositories.
